try-prepare-repo: add the --rebase-onto=<commit> option
This can be used to test the tor browser patches onto the latest firefox
developement version from the same ESR branch.

diff --git a/try-prepare-repo b/try-prepare-repo
--- a/try-prepare-repo
+++ b/try-prepare-repo
@@ -4,8 +4,23 @@ set -e
 
 basedir=$(dirname $0)
 . "$basedir/common"
-[ $# -eq 1 ] || exit 1
-COMMIT="$1"
+rebase_onto=
+COMMIT=
+while [ $# != 0 ]
+do
+    case "$1" in
+        --rebase-onto=*)
+            rebase_onto="${1#--rebase-onto=}"
+            shift
+            ;;
+        *)
+            [ -n "$COMMIT" ] && echo "Bad arguments" && exit 1
+            COMMIT="$1"
+            shift
+            ;;
+    esac
+done
+[ -z "$COMMIT" ] && echo "Missing argument" && exit 2
 
 # trychooser: http://trychooser.pub.build.mozilla.org/
 [ -z "$trychooser" ] &&
@@ -59,5 +74,7 @@ do
 done
 $hg qnew -m "$trychooser" trychooser
 rm -Rf "$patches_dir"
+[ -n "$rebase_onto" ] &&
+    $hg rebase -d "$rebase_onto" -r qbase..qtip
 rm -f "$lockdir/$hgrepo"
 echo > "$inotifydir/$hgrepo"
